### ISSUE TITLE
Question about loss function.

### ISSUE THREAD

**Issue by CVStack** [uta-smile/TVT#12]
Hi.

Thank you for sharing the code.

I have the question about the total loss function using in this code.

![image](https://user-images.githubusercontent.com/38209962/214481972-fe894645-8b98-40be-a2ac-20da9404f5a7.png)

As i know, most codes of GAN backward the generator and discriminator loss separately. However, you backward them in once by combining them into one loss. (As i understood, loss_ad_local and loss_ad_global are same with discriminator and generator loss).

Does backwarding the combined loss function have the same effect as backwarding each loss functions?

Thank you.

**Comment by viyjy** [comment]
Hi, thanks for interest in our work.
The discriminator losses are implemented by gradient reversal: https://github.com/uta-smile/TVT/blob/main/models/modeling.py#L419
Please refer to this paper: https://arxiv.org/pdf/1409.7495.pdf
Gradient reversal is different from GAN in terms of the training implementation, but they share the same idea and achieve the same goal (distinguish true examples from generated examples).

**Comment by CVStack** [comment]
I understood!

Thank you! :)
