### ISSUE TITLE
The question in transfor.py file

### ISSUE THREAD

**Issue by 23425Ning** [uta-smile/TVT#17]
Thanks for ur excellent work. And I wanna try to reproduce ur results, but there was a strange question in transform.py line 31, As belows
, I've checked this repository and found u didnt provide the file "ilsvrc_2012_mean.npy". So I tried to search on Internet and use the third file, and this happend. So I would like to ask whether it is my problem or the problem of the file  u didnt provide, so the internet version Your reply would be greatly appreciated! Thanks ur work again!
![PixPin_2024-06-25_13-26-03](https://github.com/uta-smile/TVT/assets/161605640/91f69aa6-e8e6-4b53-be14-a75d8fb57274)

**Comment by viyjy** [comment]
Hi, thanks for your interest of our work. Do you mean https://github.com/BVLC/caffe/blob/master/python/caffe/imagenet/ilsvrc_2012_mean.npy?

**Comment by 23425Ning** [comment]
> Hi, thanks for your interest of our work. Do you mean https://github.com/BVLC/caffe/blob/master/python/caffe/imagenet/ilsvrc_2012_mean.npy?

Strangely, I tried the same file yesterday, but it didnt work anyway. And, I tried ur code without "Normalize", and its performance drops one to two points. But today the link is successful to work. Whatever, Thanks a lot for ur reply, sry for my careless. Have a good Day! HaHa
