### ISSUE TITLE
No module named 'models.modeling_resnet'

### ISSUE THREAD

**Issue by ShiyeLi** [uta-smile/TVT#3]
I try to run your code, but get the error as title, and I found there is no file named 'modeling_resnet'(in the code 'import .modeling_resnet import ResNetV2'), are there any file lost? 
Thanks.

**Comment by viyjy** [comment]
Sorry, it was wrongly deleted. I just uploaded it. Please let me know if you might need further information. Thanks.

**Comment by ShiyeLi** [comment]
> Sorry, it was wrongly deleted. I just uploaded it. Please let me know if you might need further information. Thanks.

Thank you. It works.
