### ISSUE TITLE
how to load the .bin file for Attention map visualization

### ISSUE THREAD

**Issue by shaojiezhanglalala** [uta-smile/TVT#6]
Hi, sorry to bother you. I'm having trouble saving the training model file and loading the model. I can't load the files I trained and saved in the output folder,  _checkpoint.bin and _checkpoint_adv.bin. I want to load the trained model to do some visualization experiments, but I am confused about the .bin file. I can load ViT-B_16.npz normally for Attention map visualization. Can you share how you loaded the .bin file for Attention map visualization? 

here is the code to save model in your train.py.

`def save_model(args, model, is_adv=False):

model_to_save = model.module if hasattr(model, 'module') else model
    if not is_adv:
        model_checkpoint = os.path.join(args.output_dir, args.dataset, "%s_checkpoint.bin" % args.name)
    else:
        model_checkpoint = os.path.join(args.output_dir, args.dataset, "%s_checkpoint_adv.bin" % args.name)
    torch.save(model_to_save.state_dict(), model_checkpoint)
    logger.info("Saved model checkpoint to [DIR: %s]", os.path.join(args.output_dir, args.dataset))`

I'm a newbie, so I'm very sorry to bother you with this question.

**Comment by viyjy** [comment]
Hi, thanks for your interest. Please check the newly uploaded visualization code which can automatically load the .bin file

https://github.com/uta-smile/TVT/blob/main/README.md#attention-map-visualization

Or you can find more details in the README. Please let me know if you might need additional information. Thanks.

**Comment by shaojiezhanglalala** [comment]
Hi, I studied and used the visualize.py file you uploaded and it really worked! I am very happy and thank you very much for your generous help. thank you very much!

**Comment by viyjy** [comment]
no problem
